server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://ms-cv-db:3306/db_cv?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: cvuser
    password: cvpass123
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  application:
    name: ms-cv

eureka:
  instance:
    hostname: ms-cv  # IMPORTANT: nom du conteneur
    prefer-ip-address: false  # Désactivé pour Docker
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka  # CORRIGÉ: ms-discover au lieu de localhost
    fetch-registry: true
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /ms-cv/api-docs       # endpoint pour récupérer le JSON OpenAPI
  swagger-ui:
    path: /ms-cv/swagger-ui.html # endpoint pour accéder à l'interface Swagger UI
    enabled: true


logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG