server:
  port: 8088

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-user-utilisateurs
          uri: lb://ms-user
          predicates:
            - Path=/api/utilisateurs/**

        - id: ms-user-auth
          uri: lb://ms-user
          predicates:
            - Path=/api/auth/**

        - id: ms-user-etudiants
          uri: lb://ms-user
          predicates:
            - Path=/api/etudiants/**

        - id: ms-user-alumni
          uri: lb://ms-user
          predicates:
            - Path=/api/alumni/**

  eureka:
    client:
      service-url:
        defaultZone: http://ms-discover:8761/eureka
      healthcheck:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
