# server:
#   port: 8088

# spring:
#   application:
#     name: ms-gateway

#   cloud:
#     gateway:
#       server:
#         webflux:
#           routes:
#             - id: ms-user
#               uri: lb://ms-user
#               predicates:
#                 - Path=/api/v1/**
      
#       globalcors:
#         cors-configurations:
#           '[/**]':
#             allowedOrigins: "*"
#             allowedHeaders: "*"
#             allowedMethods:
#               - GET
#               - POST
#               - PUT
#               - DELETE
#               - OPTIONS

#       httpclient:
#         connect-timeout: 1000
#         response-timeout: 5s

#       discovery:
#         locator:
#           enabled: false

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka
#     healthcheck:
#       enabled: true

# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG


server:
  port: 8088

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      # Configuration webflux conservée
      server:
        webflux:
          routes:
            - id: ms-user
              uri: lb://ms-user
              predicates:
                - Path=/api/v1/**
              filters:
                - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

eureka:
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka  # CORRIGÉ: ms-discover au lieu de localhost
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: TRACE
    org.springframework.cloud.client.discovery: DEBUG
    com.netflix.discovery: DEBUG