server:
  port: 8088

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # OpenAPI JSON (doit être avant les autres routes)
        - id: openapi
          uri: lb://ms-user
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs(?<segment>/?.*), /v3/api-docs$\{segment}

        # Swagger UI
        - id: swagger-ui
          uri: lb://ms-user
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui/(?<segment>.*), /swagger-ui/$\{segment}

        # Swagger resources
        - id: swagger-resources
          uri: lb://ms-user
          predicates:
            - Path=/swagger-resources/**

        # Webjars pour Swagger
        - id: webjars
          uri: lb://ms-user
          predicates:
            - Path=/webjars/**

        # Routes API ms-user
        - id: ms-user-api
          uri: lb://ms-user
          predicates:
            - Path=/api/v1/**

  eureka:
    client:
      service-url:
        defaultZone: http://ms-discover:8761/eureka
      healthcheck:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: TRACE