server:
  port: 8088

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
         # 🔹 Swagger UI (HTML)
        - id: swagger-ui
          uri: lb://ms-user
          predicates:
            - Path=/swagger-ui.html

        # 🔹 Swagger static resources
        - id: swagger-ui-resources
          uri: lb://ms-user
          predicates:
            - Path=/swagger-ui/**

        # 🔹 OpenAPI JSON
        - id: openapi
          uri: lb://ms-user
          predicates:
            - Path=/v3/api-docs

        # 🔹 OpenAPI groups
        - id: openapi-groups
          uri: lb://ms-user
          predicates:
            - Path=/v3/api-docs/**
        
        - id: ms-user-utilisateurs
          uri: lb://ms-user
          predicates:
            - Path=/api/v1/utilisateurs/**

        - id: ms-user-auth
          uri: lb://ms-user
          predicates:
            - Path=/api/v1/auth/**

        - id: ms-user-etudiants
          uri: lb://ms-user
          predicates:
            - Path=/api/v1/etudiants/**

        - id: ms-user-alumni
          uri: lb://ms-user
          predicates:
            - Path=/api/v1/alumni/**

  eureka:
    client:
      service-url:
        defaultZone: http://ms-discover:8761/eureka
      healthcheck:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
