server:
  port: 8081  

spring:
  datasource:
    url: jdbc:mariadb://ms-user-db:3306/db_user?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: passer123
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        connection.provider_disables_autocommit: true

  application:
    name: ms-user

eureka:
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
